### ISSUE TITLE
Feature Request: Higher Limits

### ISSUE THREAD

**Issue by nettnikl** [nanmu42/limitio#1]
Hey, could you implement your read limit as a int64 or uint64 instead of int32? I'd like to limit my streams because they get very big, so i would appreciate a high limit. Thanks in advance!

**Comment by nanmu42** [comment]
Hi, limitio uses `int` instead of `int32` or `int64`, and [its size depends on the hardware archtechture](https://go.dev/ref/spec#:~:text=There%20is%20also%20a%20set%20of%20predeclared%20integer%20types%20with%20implementation%2Dspecific%20sizes%3A). I don't see it really a problem and alter it would bring a breaking public API change.

You may vendor and modify the code locally per your need since this package is tiny.

The code is released under the MIT license. Have fun.
